# Generated by Django 2.1 on 2019-09-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postdb', '0002_playerinfo_teaminfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebInfo',
        ),
    ]
