---
title: "Homeword 3"
author: "Zhang HeXiao"
date: "2020/3/26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 5.7

Two custom functions for computing CI.

```{r}
rm(list=ls())

T2.CI <- function(mat, a, alpha=0.05){
  n <- nrow(mat)
  p <- ncol(mat)
  CI <- rep(colMeans(mat)%*%a, 2)
  tmp <- sqrt(p*(n-1)/(n*(n-p))*qf(1-alpha, p, n-p)*a%*%var(mat)%*%a)
  CI <- CI + tmp*c(-1, 1)
  CI
}

Bonfer.CI <- function(mat, alpha=0.05){
  n <- nrow(mat)
  p <- ncol(mat)
  s <- var(mat)
  mu <- colMeans(mat)
  res <- matrix(nrow=p, ncol=2)
  rownames(res) <- names(mat)
  for (i in 1:p){
    res[i, ] = rep(mu[i], 2)+qt(1-alpha/(2*p), n-1)*sqrt(s[i, i]/n)*c(-1, 1)
  }
  res
}
```

Now to calculate the answer of the problem.

```{r}
data <- read.table('T5-1.DAT')
names(data) <- c("Sweat_Rate","Sodium","Potassium")

bonfer.CI <- Bonfer.CI(data)
t2.CI <- matrix(nrow=nrow(bonfer.CI), ncol=ncol(bonfer.CI))
for (i in 1:3){
  ones <- rep(0, 3)
  ones[i] <-  1
  t2.CI[i, ] <- T2.CI(data, ones)
}
rownames(t2.CI) <- names(data)

print(bonfer.CI)
print(t2.CI)
```

The following codes are used for ploting.

```{r}
# Q-Q plot
par(mfcol=c(1, 3))
for (i in 1:3){
  name = sprintf('x%d',i)
  qqnorm(data[, i], main=names(data)[i])
  qqline(data[, i])
}

# scatter plot matrix
library(GGally)
ggpairs(data)

# Chi-square plot
library(mvoutlier)
chisq.plot(data)
```

## Problem 6.7

```{r}
rm(list=ls())

p <- 2
alpha <- 0.05
  
x1.mean <-  c(204.4, 556.6)
S1 <- matrix(c(13825.3, 23823.4,
               23823.4, 73107.4),
             nrow=2, ncol=2)
n1 <- 45

x2.mean <-  c(130.0, 355.0)
S2 <- matrix(c(8632.0, 19616.7,
               19616.7, 55964.5),
             nrow=2, ncol=2)
n2 <- 55
```

### (a)

```{r}
S.pooled <- (n1-1)/(n1+n2-2)*S1+(n2-1)/(n1+n2-2)*S2

T2 <- 1/(1/n1+1/n2)*(x1.mean-x2.mean)%*%solve(S.pooled)%*%(x1.mean-x2.mean)
critical <- p*(n1+n2-2)/(n1+n2-p-1)*qf(1-alpha, p, n1+n2-p-1)

cat("T2 =", T2, ">", "c =", critical, "reject H0.\n")

(solve(S.pooled)%*%(x1.mean-x2.mean)) 
```

### (b)

```{r}
T2 <- (x1.mean-x2.mean)%*%solve(S1/n1+S2/n2)%*%(x1.mean-x2.mean)
critical <- qchisq(1-alpha, p)

cat("T2 =", T2, ">", "c =", critical, "reject H0.\n")

(solve(S1/n1+S2/n2)%*%(x1.mean-x2.mean))
```

### (c)

```{r}
g <- 2
n.arr <- c(n1, n2)

v <- p*(p+1)*(g-1)/2
u <- (2*p^2+3*p-1)/(6*(p+1)*(g-1))*
  (sum(1/(n.arr-1))-1/sum(n.arr-1))

S.p.det <- det(S.pooled)
S.arr.det <- c(det(S1), det(S2))
C <- (1-u)*(sum(n.arr-1)*log(S.p.det)-
              sum((n.arr-1)*log(S.arr.det)))

critiral <- qchisq(1-alpha, v)

cat("C =", C, ">", "c =", critical, "reject H0.\n")
```